[book]
authors = ["language learner"]
language = "zh"
src = "src"
title = "JAV 百科"



[output.html]
git-repository-url = "https://github.com/javwiki/javwiki.github.io"
edit-url-template = "https://github.com/javwiki/javwiki.github.io/edit/main/{path}"
