[project]
# BEGIN GENERATED NAV
nav = [
  "index.md",
  { "人物" = [
    "人物/index.md",
    { "女优" = [
      "人物/女优/index.md",
      { "あ行" = [
        "人物/女优/あ/index.md",
        { "あ 段 — あ行" = [
          "人物/女优/あ/あ/index.md",
          "人物/女优/あ/あ/AIKA.md",
          "人物/女优/あ/あ/あきばもも.md",
          "人物/女优/あ/あ/あずみ恋.md",
          "人物/女优/あ/あ/天海翼.md",
          "人物/女优/あ/あ/安位薰.md",
          "人物/女优/あ/あ/彩美旬果.md",
          "人物/女优/あ/あ/新有菜.md",
          "人物/女优/あ/あ/明日花绮罗.md",
          "人物/女优/あ/あ/有冈美羽.md",
          "人物/女优/あ/あ/朝桐光.md",
          "人物/女优/あ/あ/朝美穗香.md",
          "人物/女优/あ/あ/相泽南.md",
          "人物/女优/あ/あ/苍井空.md",
          "人物/女优/あ/あ/荒木レナ.md",
          "人物/女优/あ/あ/葵伊吹.md",
          "人物/女优/あ/あ/葵司.md",
          "人物/女优/あ/あ/葵百合香.md",
          "人物/女优/あ/あ/麻美由真.md",
        ] },
        { "い 段 — あ行" = [
          "人物/女优/あ/い/index.md",
          "人物/女优/あ/い/一条みお.md",
          "人物/女优/あ/い/五日市芽依.md",
          "人物/女优/あ/い/今賀はる.md",
          "人物/女优/あ/い/伊藤舞雪.md",
          "人物/女优/あ/い/市川雅美.md",
          "人物/女优/あ/い/石原希望.md",
          "人物/女优/あ/い/石川澪.md",
          "人物/女优/あ/い/饭岛爱.md",
        ] },
        { "う 段 — あ行" = [
          "人物/女优/あ/う/index.md",
          "人物/女优/あ/う/上原亚衣.md",
          "人物/女优/あ/う/宇流木さら.md",
        ] },
        { "え 段 — あ行" = [
          "人物/女优/あ/え/index.md",
        ] },
        { "お 段 — あ行" = [
          "人物/女优/あ/お/index.md",
          "人物/女优/あ/お/おりん.md",
          "人物/女优/あ/お/乙都咲乃.md",
          "人物/女优/あ/お/冲田杏梨.md",
          "人物/女优/あ/お/大槻响.md",
          "人物/女优/あ/お/奥田咲.md",
          "人物/女优/あ/お/奥菜アンナ.md",
          "人物/女优/あ/お/小仓由菜.md",
          "人物/女优/あ/お/小栗操.md",
          "人物/女优/あ/お/小泽玛利亚.md",
          "人物/女优/あ/お/小那海あや.md",
          "人物/女优/あ/お/小野六花.md",
          "人物/女优/あ/お/折原ほのか.md",
        ] },
      ] },
      { "か行" = [
        "人物/女优/か/index.md",
        { "か 段 — か行" = [
          "人物/女优/か/か/index.md",
          "人物/女优/か/か/奏音花音.md",
          "人物/女优/か/か/枫花.md",
          "人物/女优/か/か/河北彩花.md",
          "人物/女优/か/か/河合明日菜.md",
          "人物/女优/か/か/神咲诗织.md",
          "人物/女优/か/か/神崎ゆま.md",
          "人物/女优/か/か/风间由美.md",
          "人物/女优/か/か/香水纯.md",
        ] },
        { "き 段 — か行" = [
          "人物/女优/か/き/index.md",
          "人物/女优/か/き/北川ゆず.md",
          "人物/女优/か/き/北川绘里香.md",
          "人物/女优/か/き/君岛美绪.md",
          "人物/女优/か/き/君色花音.md",
          "人物/女优/か/き/君野ここ.md",
          "人物/女优/か/き/希咲エマ.md",
          "人物/女优/か/き/希岛爱理.md",
          "人物/女优/か/き/木村愛心.md",
          "人物/女优/か/き/桐嶋りの.md",
          "人物/女优/か/き/菊乃らん.md",
        ] },
        { "く 段 — か行" = [
          "人物/女优/か/く/index.md",
          "人物/女优/か/く/工藤ララ.md",
          "人物/女优/か/く/红音萤.md",
          "人物/女优/か/く/黑木香.md",
        ] },
        { "け 段 — か行" = [
          "人物/女优/か/け/index.md",
        ] },
        { "こ 段 — か行" = [
          "人物/女优/か/こ/index.md",
          "人物/女优/か/こ/九井スナオ.md",
          "人物/女优/か/こ/五条恋.md",
          "人物/女优/か/こ/児玉るみ.md",
          "人物/女优/か/こ/小凑四叶.md",
          "人物/女优/か/こ/小向美奈子.md",
          "人物/女优/か/こ/小島みなみ.md",
          "人物/女优/か/こ/香坂紗梨.md",
        ] },
      ] },
      { "さ行" = [
        "人物/女优/さ/index.md",
        { "さ 段 — さ行" = [
          "人物/女优/さ/さ/index.md",
          "人物/女优/さ/さ/佐佐木明希.md",
          "人物/女优/さ/さ/佐山爱.md",
          "人物/女优/さ/さ/岬奈奈美.md",
          "人物/女优/さ/さ/樱井步.md",
          "人物/女优/さ/さ/樱木凛.md",
          "人物/女优/さ/さ/樱空桃.md",
          "人物/女优/さ/さ/笹倉杏.md",
          "人物/女优/さ/さ/西条琉璃.md",
        ] },
        { "し 段 — さ行" = [
          "人物/女优/さ/し/index.md",
          "人物/女优/さ/し/Julia.md",
          "人物/女优/さ/し/东云美玲.md",
          "人物/女优/さ/し/城星凜.md",
          "人物/女优/さ/し/椎名空.md",
          "人物/女优/さ/し/澁谷果歩.md",
          "人物/女优/さ/し/白上咲花.md",
          "人物/女优/さ/し/白峰美羽.md",
          "人物/女优/さ/し/白浜果歩.md",
          "人物/女优/さ/し/白石茉莉奈.md",
          "人物/女优/さ/し/白鳥香里奈.md",
          "人物/女优/さ/し/篠田优.md",
          "人物/女优/さ/し/篠田步美.md",
        ] },
        { "す 段 — さ行" = [
          "人物/女优/さ/す/index.md",
          "人物/女优/さ/す/鈴村あいり.md",
        ] },
      ] },
      { "た行" = [
        "人物/女优/た/index.md",
        { "た 段 — た行" = [
          "人物/女优/た/た/index.md",
          "人物/女优/た/た/壇玲奈.md",
          "人物/女优/た/た/橘芹那.md",
          "人物/女优/た/た/泷泽萝拉.md",
          "人物/女优/た/た/玉城マイ.md",
          "人物/女优/た/た/田野忧.md",
          "人物/女优/た/た/立川理恵.md",
          "人物/女优/た/た/高桥圣子.md",
          "人物/女优/た/た/鷹宮ゆい.md",
        ] },
        { "ち 段 — た行" = [
          "人物/女优/た/ち/index.md",
          "人物/女优/た/ち/千乃あずみ.md",
        ] },
        { "つ 段 — た行" = [
          "人物/女优/た/つ/index.md",
          "人物/女优/た/つ/九十九メイ.md",
          "人物/女优/た/つ/月野りさ.md",
          "人物/女优/た/つ/月野姫.md",
          "人物/女优/た/つ/月雲よる.md",
          "人物/女优/た/つ/蕾.md",
        ] },
        { "て 段 — た行" = [
          "人物/女优/た/て/index.md",
          "人物/女优/た/て/ティア.md",
          "人物/女优/た/て/天使萌.md",
          "人物/女优/た/て/天馬ゆい.md",
        ] },
        { "と 段 — た行" = [
          "人物/女优/た/と/index.md",
          "人物/女优/た/と/东条夏.md",
          "人物/女优/た/と/冬愛ことね.md",
          "人物/女优/た/と/友田彩也香.md",
          "人物/女优/た/と/户田真琴.md",
        ] },
      ] },
      { "な行" = [
        "人物/女优/な/index.md",
        { "な 段 — な行" = [
          "人物/女优/な/な/index.md",
          "人物/女优/な/な/七泽美亚.md",
          "人物/女优/な/な/七海ひな.md",
          "人物/女优/な/な/七瀬いおり.md",
          "人物/女优/な/な/中野七绪.md",
          "人物/女优/な/な/凪ひかる.md",
          "人物/女优/な/な/成濑心美.md",
          "人物/女优/な/な/永井マリア.md",
          "人物/女优/な/な/永瀬ゆい.md",
          "人物/女优/な/な/永野一夏.md",
          "人物/女优/な/な/渚光希.md",
        ] },
        { "に 段 — な行" = [
          "人物/女优/な/に/index.md",
          "人物/女优/な/に/二宫光.md",
          "人物/女优/な/に/仁科百华.md",
          "人物/女优/な/に/新山らん.md",
          "人物/女优/な/に/西宫梦.md",
        ] },
        { "の 段 — な行" = [
          "人物/女优/な/の/index.md",
          "人物/女优/な/の/野々浦暖.md",
        ] },
      ] },
      { "は行" = [
        "人物/女优/は/index.md",
        { "は 段 — は行" = [
          "人物/女优/は/は/index.md",
          "人物/女优/は/は/初美沙希.md",
          "人物/女优/は/は/早川瀬里奈.md",
          "人物/女优/は/は/桥本有菜.md",
          "人物/女优/は/は/波多野结衣.md",
          "人物/女优/は/は/羽咲美晴.md",
          "人物/女优/は/は/羽生ありさ.md",
          "人物/女优/は/は/羽田爱.md",
          "人物/女优/は/は/莲实克蕾儿.md",
        ] },
        { "ひ 段 — は行" = [
          "人物/女优/は/ひ/index.md",
          "人物/女优/は/ひ/Hitomi.md",
          "人物/女优/は/ひ/姫咲はな.md",
          "人物/女优/は/ひ/姫川ゆうな.md",
        ] },
        { "ふ 段 — は行" = [
          "人物/女优/は/ふ/index.md",
          "人物/女优/は/ふ/冬月枫.md",
          "人物/女优/は/ふ/古川伊织.md",
          "人物/女优/は/ふ/深田咏美.md",
          "人物/女优/は/ふ/藤かんな.md",
        ] },
        { "べ 段 — は行" = [
          "人物/女优/は/べ/index.md",
          "人物/女优/は/べ/ベアトリクス.md",
        ] },
        { "ほ 段 — は行" = [
          "人物/女优/は/ほ/index.md",
          "人物/女优/は/ほ/本庄铃.md",
        ] },
      ] },
      { "ま行" = [
        "人物/女优/ま/index.md",
        { "ま 段 — ま行" = [
          "人物/女优/ま/ま/index.md",
          "人物/女优/ま/ま/松本一香.md",
          "人物/女优/ま/ま/真木今日子.md",
        ] },
        { "み 段 — ま行" = [
          "人物/女优/ま/み/index.md",
          "人物/女优/ま/み/Miru.md",
          "人物/女优/ま/み/みやび音羽.md",
          "人物/女优/ま/み/三上悠亚.md",
          "人物/女优/ま/み/三浦芽依.md",
          "人物/女优/ま/み/南梨央奈.md",
          "人物/女优/ま/み/宫下玲奈.md",
          "人物/女优/ま/み/宮島めい.md",
          "人物/女优/ま/み/未步奈奈.md",
          "人物/女优/ま/み/水卜樱.md",
          "人物/女优/ま/み/水菜丽.md",
          "人物/女优/ま/み/美乃すずめ.md",
          "人物/女优/ま/み/美園和花.md",
          "人物/女优/ま/み/美波あいり.md",
          "人物/女优/ま/み/美谷朱音.md",
          "人物/女优/ま/み/蜜美杏.md",
        ] },
        { "め 段 — ま行" = [
          "人物/女优/ま/め/index.md",
          "人物/女优/ま/め/惠理.md",
        ] },
        { "も 段 — ま行" = [
          "人物/女优/ま/も/index.md",
          "人物/女优/ま/も/守屋よしの.md",
          "人物/女优/ま/も/桃乃木香奈.md",
          "人物/女优/ま/も/桃谷りり.md",
          "人物/女优/ま/も/森ほたる.md",
          "人物/女优/ま/も/森泽佳奈.md",
          "人物/女优/ま/も/百永さりな.md",
        ] },
      ] },
      { "や行" = [
        "人物/女优/や/index.md",
        { "や 段 — や行" = [
          "人物/女优/や/や/index.md",
          "人物/女优/や/や/八掛うみ.md",
          "人物/女优/や/や/八木奈奈.md",
          "人物/女优/や/や/山手梨爱.md",
          "人物/女优/や/や/弥生みづき.md",
        ] },
        { "ゆ 段 — や行" = [
          "人物/女优/や/ゆ/index.md",
          "人物/女优/や/ゆ/优月真里奈.md",
          "人物/女优/や/ゆ/夢乃あいか.md",
          "人物/女优/や/ゆ/柚月向日葵.md",
          "人物/女优/や/ゆ/楪可怜.md",
          "人物/女优/や/ゆ/由來千歲.md",
          "人物/女优/や/ゆ/由爱可奈.md",
          "人物/女优/や/ゆ/由良かな.md",
        ] },
        { "よ 段 — や行" = [
          "人物/女优/や/よ/index.md",
          "人物/女优/や/よ/吉川爱美.md",
          "人物/女优/や/よ/吉根ゆりあ.md",
          "人物/女优/や/よ/吉泽明步.md",
          "人物/女优/や/よ/吉高宁宁.md",
          "人物/女优/や/よ/米倉穂香.md",
        ] },
      ] },
      { "ら行" = [
        "人物/女优/ら/index.md",
        { "り 段 — ら行" = [
          "人物/女优/ら/り/index.md",
          "人物/女优/ら/り/Rio.md",
          "人物/女优/ら/り/凛音とうか.md",
        ] },
      ] },
      { "わ行" = [
        "人物/女优/わ/index.md",
        { "わ 段 — わ行" = [
          "人物/女优/わ/わ/index.md",
        ] },
        { "を 段 — わ行" = [
          "人物/女优/わ/を/index.md",
        ] },
        { "ん 段 — わ行" = [
          "人物/女优/わ/ん/index.md",
        ] },
      ] },
    ] },
    { "男优" = [
      "人物/男优/index.md",
      "人物/男优/一徹.md",
      "人物/男优/加藤鹰.md",
      "人物/男优/吉村卓.md",
      "人物/男优/大島丈.md",
      "人物/男优/月野带人.md",
      "人物/男优/森林.md",
      "人物/男优/清水健.md",
    ] },
    { "导演" = [
      "人物/导演/index.md",
      "人物/导演/朝霧浄.md",
      "人物/导演/溜池ゴロー.md",
    ] },
    { "组合" = [
      "人物/组合/index.md",
      "人物/组合/BLACK_DIAMOND.md",
      "人物/组合/Million Girls Z.md",
      "人物/组合/SEXY-J.md",
      "人物/组合/me-me.md",
      "人物/组合/惠比寿★麝香葡萄.md",
      "人物/组合/桃色遊戯.md",
      "人物/组合/熟ザイル.md",
      "人物/组合/超心动♡宣传部.md",
      "人物/组合/道玄坂69.md",
    ] },
  ] },
  { "作品" = [
    "作品/index.md",
    { "单部作品" = [
      "作品/单部/index.md",
      "作品/单部/ABP-984.md",
      "作品/单部/AVOP-404.md",
      "作品/单部/EBOD-613.md",
      "作品/单部/IPX-177.md",
      "作品/单部/IPZ-612.md",
      "作品/单部/IPZ-901.md",
      "作品/单部/JUFD-387.md",
      "作品/单部/JUFD-531.md",
      "作品/单部/JUFE-016.md",
      "作品/单部/KBI-001.md",
      "作品/单部/SDDE-704.md",
      "作品/单部/SDMUA-070.md",
      "作品/单部/STARS-979.md",
    ] },
    { "系列" = [
      "作品/系列/index.md",
      "作品/系列/○○を、飼いならす。.md",
      "作品/系列/エロ痴女ナースは口内射精がお好き.md",
      "作品/系列/中出し射精執行官.md",
      "作品/系列/人妻秘書、汗と接吻に満ちた社長室中出し性交.md",
      "作品/系列/俺専用！爆乳生ハメ奴隷.md",
      "作品/系列/僕だけの巨乳女教師ペット.md",
      "作品/系列/僕と○○の異世界性活.md",
      "作品/系列/僕のペットは○○.md",
      "作品/系列/全裸家政婦.md",
      "作品/系列/出張先のビジネスホテルでずっと憧れていた女上司とまさかまさかの相部屋宿泊.md",
      "作品/系列/可愛い顔してデカ尻！！.md",
      "作品/系列/夫の上司に飾られた人妻ボディアクセサリー.md",
      "作品/系列/女子マネージャーは、僕達の性処理ペット。.md",
      "作品/系列/完全主観で楽しむ○○との新婚生活.md",
      "作品/系列/密着して舐め尽くすむしゃぶり唾液痴女.md",
      "作品/系列/射精を支配される究極主観JOI.md",
      "作品/系列/彼女のお姉さんは巨乳と中出しOKで僕を誘惑.md",
      "作品/系列/最高の愛人と、最高の中出し性交。.md",
      "作品/系列/汚された花嫁.md",
      "作品/系列/淫語で誘う寸止め焦らし痴女.md",
      "作品/系列/淫語女子アナ.md",
      "作品/系列/淫魔に精子が空になるまで毎晩吸い尽くされる.md",
      "作品/系列/絶対妊娠！ガン反り生チ○ポで孕ませ中出しSEX！.md",
      "作品/系列/絶対領域.md",
      "作品/系列/高級ランジェリー販売員の誘惑セールス術.md",
      "作品/系列/麗しのマネキン夫人.md",
    ] },
    { "番号" = [
      "作品/番号/index.md",
    ] },
  ] },
  { "产业与组织" = [
    "产业/index.md",
    { "制作集团与公司" = [
      "产业/制作公司/index.md",
      "产业/制作公司/KMP.md",
      "产业/制作公司/Prestige.md",
      "产业/制作公司/SOD.md",
      "产业/制作公司/WILL.md",
    ] },
    { "制作厂牌" = [
      "产业/厂牌/index.md",
      "产业/厂牌/Attackers.md",
      "产业/厂牌/IdeaPocket.md",
      "产业/厂牌/KANBi.md",
      "产业/厂牌/MOODYZ.md",
      "产业/厂牌/S1 NO.1 STYLE.md",
    ] },
    { "经纪公司" = [
      "产业/经纪公司/index.md",
      "产业/经纪公司/8MAN.md",
      "产业/经纪公司/ACT Promotion.md",
      "产业/经纪公司/AINA Group.md",
      "产业/经纪公司/ARROWS.md",
      "产业/经纪公司/Allpro.md",
      "产业/经纪公司/Bambi Promotion.md",
      "产业/经纪公司/Bstar.md",
      "产业/经纪公司/C-more.md",
      "产业/经纪公司/CRUSE GROUP.md",
      "产业/经纪公司/Diaz Group.md",
      "产业/经纪公司/HANAYA PROJECT.md",
      "产业/经纪公司/JETSTREAM.md",
      "产业/经纪公司/LIFE PROMOTION.md",
      "产业/经纪公司/LIGHT.md",
      "产业/经纪公司/LINX.md",
      "产业/经纪公司/Mine_S.md",
      "产业/经纪公司/NAX.md",
      "产业/经纪公司/Prime Agency.md",
      "产业/经纪公司/T-POWERS.md",
      "产业/经纪公司/アトラクティブ.md",
      "产业/经纪公司/カプセルエージェンシー.md",
      "产业/经纪公司/ハーベスターズ.md",
    ] },
    { "行业协会" = [
      "产业/协会/index.md",
      "产业/协会/AV人権倫理機構.md",
      "产业/协会/ぱっぷす.md",
      "产业/协会/プロダクション協会（SPA）.md",
      "产业/协会/日本プロダクション協会.md",
    ] },
  ] },
  { "资料" = [
    "资料/index.md",
    { "奖项" = [
      "资料/奖项/index.md",
      "资料/奖项/ADULTOPIA.md",
      "资料/奖项/fanza.md",
      "资料/奖项/skypa.md",
    ] },
    { "活动" = [
      "资料/活动/index.md",
      "资料/活动/AEE.md",
      "资料/活动/JAE.md",
      "资料/活动/TAE.md",
      "资料/活动/TRE.md",
      "资料/活动/TSE.md",
      "资料/活动/上海国际成人用品展.md",
    ] },
    { "排名" = [
      "资料/排名/index.md",
    ] },
    { "法律" = [
      "资料/法律/index.md",
      "资料/法律/AV出演被害防止・救済法.md",
      "资料/法律/リベンジポルノ防止法.md",
      "资料/法律/人身売買禁止条約.md",
      "资料/法律/児童買春・児童ポルノ禁止法.md",
      "资料/法律/労働者派遣法.md",
      "资料/法律/困難女性支援法.md",
      "资料/法律/売春防止法.md",
      "资料/法律/民法.md",
      "资料/法律/職業安定法.md",
      "资料/法律/風俗営業法.md",
    ] },
    { "术语" = [
      "资料/术语/index.md",
    ] },
  ] },
  { "专题" = [
    "专题/index.md",
    "专题/AV女优与TikTokLIVE.md",
    "专题/制作公司与集团.md",
    "专题/厂商概览.md",
    "专题/日本网站对海外提供服务的限制.md",
    "专题/自杀女优.md",
  ] },
]
# END GENERATED NAV
site_name = "JAV 百科"
site_url = "https://javwiki.github.io/zh/"
site_description = "JAV（日本成人视频）综合百科。"
site_author = "javwiki contributors"
repo_url = "https://github.com/javwiki/javwiki.github.io"
repo_name = "javwiki/javwiki.github.io"
edit_uri = "edit/main/docs/zh/"
docs_dir = "docs/zh"
site_dir = "site/zh"
use_directory_urls = true

[project.extra]
alternate = [
  { name = "日本語", link = "/", lang = "ja" },
  { name = "中文", link = "/zh/", lang = "zh" },
  { name = "English", link = "/en/", lang = "en" },
]

[project.theme]
variant = "classic"
language = "zh"
custom_dir = "overrides"
features = [
  "navigation.instant",
  "navigation.prune",
  "navigation.path",
  "navigation.indexes",
  "navigation.sections",
  "navigation.top",
  "search.highlight",
]

# Follow the user's system color preference by default.
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "切换到浅色模式"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "切换到深色模式"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "跟随系统设置"

[project.plugins.tags]

[project.markdown_extensions]
attr_list = {}
md_in_html = {}
toc.permalink = true
